### ISSUE TITLE
Refresh through actuator throws an exception 'Error binding spring.config.import'

### ISSUE THREAD

**Issue by ruospalo** [spring-cloud/spring-cloud-commons#1062]
Spring cloud config client throws an exception when try to refresh the properties loaded 
through spring.config.import=configserver:http://localhost:8080

```shell
 curl -X POST http://localhost:8888/actuator/refresh
```

```shell
java.lang.NullPointerException: Cannot invoke "org.springframework.boot.context.properties.source.ConfigurationPropertySource.getConfigurationProperty(org.springframework.boot.context.properties.source.ConfigurationPropertyName)" because "source" is null
	at org.springframework.boot.context.properties.bind.Binder.findProperty(Binder.java:444) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:390) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:340) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:329) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:259) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:246) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor.getConfigImportArray(ConfigDataMissingEnvironmentPostProcessor.java:113) ~[spring-cloud-commons-3.0.4.jar:3.0.4]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor.propertySourceWithConfigImport(ConfigDataMissingEnvironmentPostProcessor.java:108) ~[spring-cloud-commons-3.0.4.jar:3.0.4]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor$$Lambda$273/0x00000000e0319790.test(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor.getConfigImports(ConfigDataMissingEnvironmentPostProcessor.java:98) ~[spring-cloud-commons-3.0.4.jar:3.0.4]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor.postProcessEnvironment(ConfigDataMissingEnvironmentPostProcessor.java:77) ~[spring-cloud-commons-3.0.4.jar:3.0.4]
	at org.springframework.cloud.context.refresh.ConfigDataContextRefresher.updateEnvironment(ConfigDataContextRefresher.java:92) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:101) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:94) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.endpoint.RefreshEndpoint.refresh(RefreshEndpoint.java:41) ~[spring-cloud-context-3.0.4.jar:3.0.4]
 ```

There is a basic example here [here](https://github.com/ruospalo/sprint-cloud-config-test)
I've also tested with the latest version of spring cloud.

Thank you very much in advance

**Comment by spencergibb** [comment]
@philwebb or @mbhave any reason this fails

https://github.com/spring-cloud/spring-cloud-commons/blob/1ce1201e9d612d8c82d7581cc3d37f117de6126e/spring-cloud-commons/src/main/java/org/springframework/cloud/commons/ConfigDataMissingEnvironmentPostProcessor.java#L113-L121

With 
```
spring.config.import:
 - configserver:http://localhost:8888
```
and does not with
```
spring.config.import: configserver:http://localhost:8888
```

**Comment by ryanjbaxter** [comment]
@spencergibb this only fails on refresh?

**Comment by spencergibb** [comment]
yes

**Comment by ryanjbaxter** [comment]
OK I knew it sounded familiar, its similar to https://github.com/spring-cloud/spring-cloud-config/issues/1849, but the problem there was when we actually started the application.

**Comment by spencergibb** [comment]
it's an issue in the new code that was introduced here to fix that one.

**Comment by philwebb** [comment]
This looks like a bug on our side. I'm still digging, but `Context` has `source = Arrays.asList((ConfigurationPropertySource) null)` which is the read unguarded.

**Comment by spencergibb** [comment]
thanks @philwebb for looking at this

**Comment by philwebb** [comment]
I was wrong, it's not a Spring Boot bug (but we could be better about dealing with it). The `ConfigDataMissingEnvironmentPostProcessor` is going over each property source and calling `ConfigurationPropertySource.from(propertySource)`. That method can return `null` if the source is that `ConfigurationPropertySourcesPropertySource`.

I think you can update `propertySourceWithConfigImport` so that is returns `false` if `ConfigurationPropertySource.from(propertySource)` returns `null`.

**Comment by spencergibb** [comment]
Thanks. Will do
