### ISSUE TITLE
Support custom HTTP status codes in LoadBalancerLifecycle

### ISSUE THREAD

**Issue by curfew117** [spring-cloud/spring-cloud-commons#1066]
In my current project, one of our microservices calls a REST Api of an another microservice and in an error scenario it returns a custom(469) error code.

I'm using a load balanced rest template in the calling service and its throwing an IllegalArgumentException error since 469 error code is not present in HttpStatus enum.

Is there any workaround to resolve this like using raw status codes instead of converting it into an enum?

`java.lang.IllegalArgumentException: No matching constant for [469]
	at org.springframework.http.HttpStatus.valueOf(HttpStatus.java:547)
	at org.springframework.http.client.AbstractClientHttpResponse.getStatusCode(AbstractClientHttpResponse.java:33)
	at org.springframework.cloud.client.loadbalancer.ResponseData.<init>(ResponseData.java:68)
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.getClientResponse(BlockingLoadBalancerClient.java:120)
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.execute(BlockingLoadBalancerClient.java:94)
	at org.springframework.cloud.client.loadbalancer.RetryLoadBalancerInterceptor.lambda$intercept$2(RetryLoadBalancerInterceptor.java:129)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:225)
	at org.springframework.cloud.client.loadbalancer.RetryLoadBalancerInterceptor.intercept(RetryLoadBalancerInterceptor.java:79)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93)
	at org.springframework.boot.actuate.metrics.web.client.MetricsClientHttpRequestInterceptor.intercept(MetricsClientHttpRequestInterceptor.java:86)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93)
	at org.springframework.cloud.sleuth.instrument.web.mvc.TracingClientHttpRequestInterceptor.intercept(TracingClientHttpRequestInterceptor.java:69)
	at org.springframework.cloud.sleuth.instrument.web.client.LazyTraceClientHttpRequestInterceptor.intercept(LazyTraceClientHttpRequestInterceptor.java:51)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93)
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:77)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:776)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:670)`

**Comment by OlgaMaciaszek** [comment]
Hello @curfew117, thanks for reporting this. It does make sense to support custom HTTP status codes. Since `2022.x` is going to be a major release, I'm going to switch to using raw status codes there.

**Comment by curfew117** [comment]
Hi @OlgaMaciaszek,

Sorry for asking but is it possible to get this this fix in 2021 release stream?
Since 2022 requires Spring Boot 3, I won't be able to upgrade to it anytime soon

Thanks in advance

**Comment by curfew117** [comment]
Thanks a ton @OlgaMaciaszek
