### ISSUE TITLE
IllegalStateException thrown when ribbonRestClient gets destroyed

### ISSUE THREAD

**Issue by sslavic** [spring-cloud/spring-cloud-commons#111]
_From @sslavic on May 10, 2016 13:13_

After upgrade of spring-cloud-netflix from 1.1.0.M5 to 1.1.0.RC1 or 1.1.0.RC2 my test logs got polluted with IllegalStateException being thrown every time context is closed and ribbonRestClient bean destroyed. Here's an example snippet, with DEBUG logging turned on:

```
15:02:04 [DEBUG] [o.s.b.f.s.DisposableBeanAdapter] [] Invoking destroy method 'shutdown' on bean with name 'ribbonRestClient'
15:02:04 [INFO ] [c.n.u.c.ShutdownEnabledTimer] [] Shutdown hook removed for: NFLoadBalancer-PingTimer-foo_service
15:02:04 [INFO ] [c.n.u.c.ShutdownEnabledTimer] [] Exception caught (might be ok if at shutdown)
java.lang.IllegalStateException: Shutdown in progress
    at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
    at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
    at com.netflix.util.concurrent.ShutdownEnabledTimer.cancel(ShutdownEnabledTimer.java:70)
    at com.netflix.loadbalancer.BaseLoadBalancer.cancelPingTask(BaseLoadBalancer.java:599)
    at com.netflix.loadbalancer.BaseLoadBalancer.shutdown(BaseLoadBalancer.java:897)
    at com.netflix.loadbalancer.DynamicServerListLoadBalancer.shutdown(DynamicServerListLoadBalancer.java:375)
    at com.netflix.niws.client.http.RestClient.shutdown(RestClient.java:725)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:354)
```

_Copied from original issue: spring-cloud/spring-cloud-netflix#1014_

**Comment by sslavic** [comment]
In RC1 and RC2, ribbon dependencies got upgraded (to 2.1.3 and 2.1.5 respectively), but downgrading them to 2.1.0, which was used in M5, did not eliminate the unwanted behavior.

**Comment by sslavic** [comment]
Using spring-cloud-context 1.1.0.M5 with spring-cloud-netflix 1.1.0.RC2 caused exception not to be thrown.

**Comment by sslavic** [comment]
Seems issue has been introduced in spring-cloud-context 1.1.0.RC1

**Comment by sslavic** [comment]
Tried 1.1.0 Brixton BUILD SNAPSHOT, same issue there:

```
16:12:04 [DEBUG] [o.s.b.f.s.DisposableBeanAdapter] [] Invoking destroy method 'shutdown' on bean with name 'ribbonLoadBalancer'
16:12:04 [INFO ] [c.n.u.c.ShutdownEnabledTimer] [] Shutdown hook removed for: NFLoadBalancer-PingTimer-foo_service
16:12:04 [INFO ] [c.n.u.c.ShutdownEnabledTimer] [] Exception caught (might be ok if at shutdown)
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at com.netflix.util.concurrent.ShutdownEnabledTimer.cancel(ShutdownEnabledTimer.java:70)
	at com.netflix.loadbalancer.BaseLoadBalancer.cancelPingTask(BaseLoadBalancer.java:614)
	at com.netflix.loadbalancer.BaseLoadBalancer.shutdown(BaseLoadBalancer.java:886)
	at com.netflix.loadbalancer.DynamicServerListLoadBalancer.shutdown(DynamicServerListLoadBalancer.java:375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:354)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:277)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:972)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:979)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1006)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:982)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:934)
	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:66)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:262)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:972)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:979)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1006)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:982)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:901)
```

**Comment by dsyer** [comment]
It's only an INFO log, so it's probably ignorable. Can you create a simple sample to reproduce the issue?

**Comment by sslavic** [comment]
Issue is still there in 1.1.1. Still struggling to find time to create sample project that reproduces it.

**Comment by sslavic** [comment]
Couldn't reproduce this anymore

**Comment by zsoltm** [comment]
@sslavic we still have this issue with 1.1.1. Got this every time with a simple load-balanced rest client, the only precondition is that there must be at least one request executed by the client before shutdown.

java.lang.IllegalStateException: Shutdown in progress
		at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82) ~[na:1.8.0_91]
		at java.lang.Runtime.removeShutdownHook(Runtime.java:239) ~[na:1.8.0_91]
		at com.netflix.util.concurrent.ShutdownEnabledTimer.cancel(ShutdownEnabledTimer.java:70) ~[netflix-commons-util-0.1.1.jar:na]
		at com.netflix.loadbalancer.BaseLoadBalancer.cancelPingTask(BaseLoadBalancer.java:614) [ribbon-loadbalancer-2.2.0.jar:2.2.0]
		at com.netflix.loadbalancer.BaseLoadBalancer.shutdown(BaseLoadBalancer.java:886) [ribbon-loadbalancer-2.2.0.jar:2.2.0]
		at com.netflix.loadbalancer.DynamicServerListLoadBalancer.shutdown(DynamicServerListLoadBalancer.java:274) [ribbon-loadbalancer-2.2.0.jar:2.2.0]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
		at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:364) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:287) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:975) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:982) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1028) [spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1004) [spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:956) [spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:70) [spring-cloud-context-1.1.1.RELEASE.jar:1.1.1.RELEASE]
		at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:272) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:975) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:982) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1028) [spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1004) [spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:923) [spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]

**Comment by dsyer** [comment]
If you look at the log out put you will see this:

```
2016-08-16 17:03:53.659  INFO 479 --- [       Thread-3] c.n.u.concurrent.ShutdownEnabledTimer    : Exception caught (might be ok if at shutdown)
```

followed by the stack trace above. It's in netflix code and it says it's OK to ignore it. If you don't want to ignore it then I guess you might need to raise an issue in Ribbon.

**Comment by zsoltm** [comment]
@dsyer Yes, it's not serious at all, but if there is a chance to shut it down gracefully, that would be great.

**Comment by dsyer** [comment]
Feel free to experiment with it and send a PR if we can fix it here (I doubt it, but it won't hurt to try).

**Comment by ryanjbaxter** [comment]
Please comment is there is anything else that needs to be done and we can reopen this issue
