### ISSUE TITLE
[Question]RoundRobinLoadBalancer+HealthCheckServiceInstanceListSupplier always one health instance returned

### ISSUE THREAD

**Issue by GrapeBaBa** [spring-cloud/spring-cloud-commons#1157]
Question

I use the spring cloud load balancer library in one standalone project without any other spring dependency. I implements a static list based `ServiceInstanceSupplier` and use `HealthCheckServiceInstanceListSupplier` wrap it. Pass the `HealthCheckServiceInstanceListSupplier` to the `RoundRobinLoadBalancer`. I expect request can select health instances in round-robin style, however I observed in my test the `HealthCheckServiceInstanceListSupplier` always returned first health instance to `RoundRobinLoadBalancer`. Am I missing anything?

**Comment by GrapeBaBa** [comment]
My customize `Supplier`.

```java
public class NodeServiceInstanceListSupplier implements ServiceInstanceListSupplier {

    private final List<ServiceInstance> serviceInstances;

    private final String chainId;

    /**
     * Constructor of NodeServiceInstanceListSupplier with chainId and list of service instances.
     *
     * @param chainId          chainId which SDK connects.
     * @param serviceInstances chain node addresses which SDK connects.
     */
    public NodeServiceInstanceListSupplier(String chainId, List<ServiceInstance> serviceInstances) {
        this.serviceInstances = serviceInstances;
        this.chainId = chainId;
    }

    @Override
    public String getServiceId() {
        return this.chainId;
    }

    @Override
    public Flux<List<ServiceInstance>> get() {
        return Flux.just(this.serviceInstances);
    }
}
```

**Comment by GrapeBaBa** [comment]
My load balancer wrapper

```java
public class NodeLoadBalancer {

    private final RoundRobinLoadBalancer roundRobinLoadBalancer;

    /**
     * Constructor of NodeLoadBalancer
     *
     * @param chainId
     * @param urls
     * @param algo
     */
    public NodeLoadBalancer(String chainId, List<String> urls, AlgoUtil.AlgoEnum algo) {
        final LoadBalancerClientsProperties loadBalancerClientsProperties = new LoadBalancerClientsProperties();
        final LoadBalancerProperties loadBalancerProperties = new LoadBalancerProperties();
        loadBalancerProperties.getHealthCheck().setInterval(Duration.ofSeconds(1));
        loadBalancerClientsProperties.getClients().put(chainId, loadBalancerProperties);
        loadBalancerClientsProperties.getHealthCheck().setInterval(Duration.ofSeconds(1));
        final ReactiveLoadBalancer.Factory<ServiceInstance> clientFactory = new LoadBalancerClientFactory(loadBalancerClientsProperties);

        List<ServiceInstance> serviceInstances = urls.stream().map((Function<String, ServiceInstance>) url -> new NodeServiceInstance(url, chainId, algo)).collect(Collectors.toList());
        //TODO: generate query api health check interface
        final ServiceInstanceListSupplier serviceInstanceListSupplier =
                new HealthCheckServiceInstanceListSupplier(new NodeServiceInstanceListSupplier(chainId, serviceInstances), clientFactory, (serviceInstance, path) -> {
                    NodeServiceInstance nodeServiceInstance = (NodeServiceInstance) serviceInstance;
                    if (nodeServiceInstance.getPort() == 8080) {
                        return Mono.just(false);
                    } else {
                        return Mono.just(true);
                    }
                });

        this.roundRobinLoadBalancer = new RoundRobinLoadBalancer(new SimpleObjectProvider<>(serviceInstanceListSupplier), chainId);
    }

    @SuppressWarnings("ConstantConditions")
    public Optional<WsClient> chooseWSClient() {
        Response<ServiceInstance> res = this.roundRobinLoadBalancer.choose().block();
        if (res instanceof EmptyResponse) {
            return Optional.empty();
        }

        return Optional.ofNullable(((NodeServiceInstance) res.getServer()).getWsClient());
    }

    /**
     * @return
     */
    @SuppressWarnings("ConstantConditions")
    public Optional<Client> chooseClient() {
        Response<ServiceInstance> res = this.roundRobinLoadBalancer.choose().block();
        if (res instanceof EmptyResponse) {
            return Optional.empty();
        }

        return Optional.ofNullable(((NodeServiceInstance) res.getServer()).getClient());
    }

```

**Comment by GrapeBaBa** [comment]
My test

```java
class NodeLoadBalancerTest {
    private static final String CHAIN_ID = "TEST_CHAIN";

    private static final List<String> urls = Lists.newArrayList();

    @BeforeAll
    static void beforeAll() {
        urls.add("http://localhost:8080");
        urls.add("http://localhost:8081");
        urls.add("http://localhost:8082");
        urls.add("http://localhost:8083");
    }

    @AfterAll
    static void afterAll() {
        urls.clear();
    }

    @Test
    void chooseWSClient() {

    }

    @Test
    void chooseClient() {
        NodeLoadBalancer nodeLoadBalancer = new NodeLoadBalancer(CHAIN_ID, urls, AlgoUtil.AlgoEnum.STD);
        try {
            TimeUnit.SECONDS.sleep(5);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Optional<Client> node1Opt = nodeLoadBalancer.chooseClient();
        assertTrue(node1Opt.isPresent());
        assertEquals(CHAIN_ID, node1Opt.get().chainID);
        assertEquals("http://localhost:8081", node1Opt.get().queryApi.getApiClient().getBasePath());

        Optional<Client> node2Opt = nodeLoadBalancer.chooseClient();
        assertTrue(node2Opt.isPresent());
        assertEquals(CHAIN_ID, node2Opt.get().chainID);
//        assertEquals("http://localhost:8081", node2Opt.get().queryApi.getApiClient().getBasePath());

        Optional<Client> node3Opt = nodeLoadBalancer.chooseClient();
        assertTrue(node3Opt.isPresent());
        assertEquals(CHAIN_ID, node3Opt.get().chainID);
        assertEquals("http://localhost:8082", node3Opt.get().queryApi.getApiClient().getBasePath());
        Optional<Client> node4Opt = nodeLoadBalancer.chooseClient();
        assertTrue(node4Opt.isPresent());
        assertEquals(CHAIN_ID, node4Opt.get().chainID);
        assertEquals("http://localhost:8083", node4Opt.get().queryApi.getApiClient().getBasePath());
    }
}
```

**Comment by GrapeBaBa** [comment]
Always returned first health instance.
```sh
org.opentest4j.AssertionFailedError: 
Expected :http://localhost:8083
Actual   :http://localhost:8081
<Click to see difference>


	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at com.loong.erhai.sdk.NodeLoadBalancerTest.chooseClient(NodeLoadBalancerTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by GrapeBaBa** [comment]
Fixed. Since I don't use spring IOC, I forgot to call `afterPropertiesSet` method manually.
