### ISSUE TITLE
ClassNotFoundException: com.github.benmanes.caffeine.cache.WSSMSA when run as native with grallvm

### ISSUE THREAD

**Issue by ashraf-revo** [spring-cloud/spring-cloud-commons#1193]
**Describe the bug**
iam getting this error when running native output 
this only happen when using caffeine
```
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.WSSMSA
	at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1132) ~[gateway-error:na]
	at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1105) ~[gateway-error:na]
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:84) ~[na:na]
	... 45 common frames omitted
```
 

**Sample**
this is a simple code that showing the error https://github.com/ashraf-revo/gateway-error.

**Comment by OlgaMaciaszek** [comment]
Hello @ashraf-revo, thanks for reporting the issue. I was able to reproduce it. I will temporarily add some hints for Caffeine to SC Commons. They will then ultimately have to be moved over to GraalVM reachability metadata.

**Comment by ashraf-revo** [comment]
thanks @OlgaMaciaszek
