### ISSUE TITLE
Missing native hints for TextEncryptorUtils

### ISSUE THREAD

**Issue by nhmarujo** [spring-cloud/spring-cloud-commons#1245]
**Describe the bug**
When I build a native image  with a jks file to use with [Spring Cloud Decryption](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_encryption_and_decryption) it fails to boot with the following error:
```java
21:26:44.825 [main] ERROR org.springframework.boot.SpringApplication -- Application run failed
java.lang.NullPointerException: null
        at org.springframework.cloud.context.encrypt.EncryptorFactory.create(EncryptorFactory.java:55)
        at org.springframework.cloud.bootstrap.encrypt.TextEncryptorUtils.getTextEncryptor(TextEncryptorUtils.java:66)
        at org.springframework.cloud.bootstrap.encrypt.TextEncryptorUtils.decrypt(TextEncryptorUtils.java:51)
        at org.springframework.cloud.bootstrap.encrypt.DecryptEnvironmentPostProcessor.postProcessEnvironment(DecryptEnvironmentPostProcessor.java:66)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
        at java.base@17.0.6/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:355)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294)
        at com.sample.jksnative.JksNativeApplication.main(JksNativeApplication.java:16)
```

Originally I had a different error that was reported and got fixed [on the framework itself](https://github.com/spring-projects/spring-framework/issues/30628), but now I get this new different error and [I was advised](https://github.com/spring-projects/spring-framework/issues/30628#issuecomment-1586820979) to report it here.

I manage to make the application work if I register the following hint:
```java
hints.reflection()
    .registerTypeIfPresent(classLoader, "org.springframework.security.rsa.crypto.RsaSecretEncryptor", INVOKE_DECLARED_CONSTRUCTORS);
```

Looks like spring cloud is missing to register some hints. Could you please take a look if that is the case? Thank you

**Sample**
I patched the original sample I used for https://github.com/spring-projects/spring-framework/issues/30628 and created a [new branch](https://github.com/nhmarujo/jks-native/tree/30628-try-spring-framework-fix) on which you can replicate the error I showed previously.

**Comment by OlgaMaciaszek** [comment]
Hi. @nhmarujo. Thanks for reporting the issue and suggesting a fix. I have added the missing hint and verified the solution.

**Comment by nhmarujo** [comment]
Hi @OlgaMaciaszek. Thank you so much for the fix 🙂
