### ISSUE TITLE
Under load LogbackLoggingSystem fails with java.io.IOException: Stream Closed when refreshing the Spring Context

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-commons#128]
See https://github.com/spring-projects/spring-boot/issues/6831. I have a feeling this is probably a Spring Cloud issue but I'm happy to reopen the Boot one if necessary.

---

Hi,

When using Spring Boot 1.4 & Spring Cloud Brixton.SR5 and POSTing to the /refresh actuator endpoint under load you get the following error:

```
ERROR in c.q.l.c.recovery.ResilientFileOutputStream@862013521 - IO failure while writing to file [app.log] java.io.IOException: Stream Closed
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:152)
    at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:72)
    at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:50)
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:106)
    at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:289)
    at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:262)
    at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:231)
    at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:207)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
    at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
    at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
    at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:335)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
    at org.springframework.cloud.context.refresh.ContextRefresher.addConfigFilesToEnvironment(ContextRefresher.java:67)
    at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:53)
    at org.springframework.cloud.endpoint.RefreshEndpoint.refresh(RefreshEndpoint.java:46)
    at org.springframework.cloud.endpoint.RefreshEndpoint.invoke(RefreshEndpoint.java:52)
```

I have created a bitbucket example https://bitbucket.org/davidmelia/spring-boot-refresh-logback-bug
1. Check out https://bitbucket.org/davidmelia/spring-boot-refresh-logback-bug as a maven project
2. Run the boot app
3. Run the com.example.StressApp main method which stresses the app and gets log generation going.
4. Run curl -X POST http://localhost:8080/refresh     (the error can sometimes be immediate but you may have to do up to 15 times to get it)

Thanks

P.S. As the error seems to originate in a Spring Boot Class (LogbackLoggingSystem) I wasn't sure if to raise this with the Spring Cloud team or yourself - I can move it if needs be :-)

**Comment by mhmxs** [comment]
I have the same issue on Spring Boot.

**Comment by mouminoux** [comment]
Hi @philwebb 

I have a similar issue, while refreshing all my log level are null and all debug logs are logged.
Did you find a workaround ?

**Comment by aukevanleeuwen** [comment]
I have the same thing if I run my tests with `debug` level on the root logger. It's intermittent, so workable because I normally don't run my tests at `debug`, but annoying nonetheless.

**Comment by spencergibb** [comment]
@davidmelia is this still an issue in Finchley or later?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
