### ISSUE TITLE
HeartbeatMonitor.update NullPointerException

### ISSUE THREAD

**Issue by bryan-helm** [spring-cloud/spring-cloud-commons#129]
If not passing the index for spring-cloud-consul-discovery blocking catalog services, then the heartbeat gets null returned for the index value, which it uses for the heartbeat event. The HeartbeatMonitor logs a NullPointerException when receiving the null index as the event value. I think the HeartbeatMonitor needs a null check on the incoming value object.

Using spring-cloud Brixton.SR5 with Consul, which brings in spring-cloud-consul 1.0.2.RELEASE, here is the top of the stack trace:

    java.lang.NullPointerException: null
        at org.springframework.cloud.client.discovery.event.HeartbeatMonitor.update(HeartbeatMonitor.java:37) ~[spring-cloud-commons-1.1.1.RELEASE.jar!/:1.1.1.RELEASE]
        at org.springframework.cloud.netflix.zuul.ZuulProxyConfiguration$ZuulDiscoveryRefreshListener.resetIfNeeded(ZuulProxyConfiguration.java:184) ~[spring-cloud-netflix-core-1.1.5.RELEASE.jar!/:1.1.5.RELEASE]
        at org.springframework.cloud.netflix.zuul.ZuulProxyConfiguration$ZuulDiscoveryRefreshListener.onApplicationEvent(ZuulProxyConfiguration.java:178) ~[spring-cloud-netflix-core-1.1.5.RELEASE.jar!/:1.1.5.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) ~[spring-context-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) ~[spring-context-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381) ~[spring-context-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335) ~[spring-context-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
        at org.springframework.cloud.consul.discovery.ConsulCatalogWatch.catalogServicesWatch(ConsulCatalogWatch.java:74) ~[spring-cloud-consul-discovery-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
    ...

**Comment by spencergibb** [comment]
@bryan-helm I'm interested in when the value is null also.

**Comment by bryan-helm** [comment]
Running local -dev agent, catalogServicesWatch (method at bottom of stack trace snippet) is using response.getConsulIndex() as the event payload, and it is null. The reason it is null is that we are trying to do failover across data centers, so are using a consul-api.1.1.0 QueryParams instance that has a datacenter. There is no provision in QueryParams to be able to set wait time or index if datacenter is set, so I am guessing the catalog service does not return an index unless one of those is set. Notice the consulIndex is checked for null before being sent as the event payload anyway in catalogServicesWatch.

BTW, thanks for the quick fix!

**Comment by spencergibb** [comment]
Thanks for the explanation!

**Comment by bryan-helm** [comment]
We found the null index was actually due to using the index returned from a catalog service get datacenters call (which is always null since it does not support blocking) instead of the one from a get services call. The services call has a non-null index, and we are using that now. But a null check on the monitor shouldn't hurt anything, so thanks for that anyway.
