### ISSUE TITLE
Spring boot 2 can't start with spring-cloud-starter

### ISSUE THREAD

**Issue by clemstoquart** [spring-cloud/spring-cloud-commons#279]
Hello,

While migrating a Spring boot 1.5 app to Spring boot 2 M7, I noticed that the `spring-cloud-starter` dependency make the app startup failed.

```
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:161)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:102)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:68)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:350)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
```
I've been able to reproduce it with `Dalston.SR4` and `Edgware.RELEASE`.

You can reproduce it easily with that sample : https://github.com/clemstoquart/spring-boot-sample/tree/spring-boot-2

 Have a nice day :)

**Comment by spencergibb** [comment]
Edgware and Dalston are not compatible with spring boot 2. Use Finchley.M5

**Comment by clemstoquart** [comment]
Sorry, I should have figured this out by myself.

Thanks for the very quick reply :)
