### ISSUE TITLE
spring boot 2.0.0.M7 support

### ISSUE THREAD

**Issue by eric239** [spring-cloud/spring-cloud-commons#281]
Latest spring cloud (`2.0.0.M5`) is broken with respect to the latest spring boot (`2.0.0.M7`). The issue is described [in this SO question](https://stackoverflow.com/questions/47593355/spring-onenabledendpointcondition-may-only-be-used-on-bean-methods-that-return) but there was no indication when it is expected to be addressed, so I feel this hiccup should be tracked as a proper issue.
The problem didn't exist in cloud `2.0.0.M4` with boot `2.0.0.M6`.

The quick summary of the issue is this exception during app context loading:
```
Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration.environmentWebEndpointExtension
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:109)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:179)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:141)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:328)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:751)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:387)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:138)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 24 more
Caused by: java.lang.IllegalStateException: Failed to extract endpoint id for org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration.environmentWebEndpointExtension
	at org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnEnabledEndpointCondition.getEndpointAttributes(OnEnabledEndpointCondition.java:78)
	at org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnEnabledEndpointCondition.getEndpointAttributes(OnEnabledEndpointCondition.java:63)
	at org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnEnabledEndpointCondition.getMatchOutcome(OnEnabledEndpointCondition.java:49)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	... 40 more
Caused by: java.lang.IllegalStateException: OnEnabledEndpointCondition may only be used on @Bean methods that return @Endpoint, @JmxEndpointExtension, or @WebEndpointExtension
	at org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnEnabledEndpointCondition.extractEndpointAttributes(OnEnabledEndpointCondition.java:97)
	at org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnEnabledEndpointCondition.getEndpointAttributes(OnEnabledEndpointCondition.java:73)
	... 43 more
```

**Comment by spencergibb** [comment]
My guess is you have some mixed dependencies. spring cloud `2.0.0.M5` doesn't exist. Do you mean spring-cloud commons? Are you using the Finchley.M5 (unannounced) release train?

**Comment by eric239** [comment]
@spencergibb my bad -- should've been more specific -- I'm using spring-cloud-sleuth (which has `2.0.0.M5` release; the actual problematic code is in `spring-cloud-context` module).
I'm a bit confused regarding `Finchley` vs using milestone versions directly -- is the latter not recommended/supported?

**Comment by spencergibb** [comment]
It is recommended to use the release train, otherwise you have to match up versions that work together and you might get errors like you mentioned.

**Comment by eric239** [comment]
Pardon my confusion -- when I look at https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-sleuth/ there're no `Finchley` versions there, so how can I use it?

**Comment by spencergibb** [comment]
http://projects.spring.io/spring-cloud/

**Comment by eric239** [comment]
Ahh I see now, the repository / dependencies setup is more complex (I was trying to backdoor in). Thanks for pointing that out. Closing this issue.
