### ISSUE TITLE
NullpointerException when rebinding context when context contains proxied bean without implementation

### ISSUE THREAD

**Issue by Dav1dde** [spring-cloud/spring-cloud-commons#337]
```java
java.lang.NullPointerException
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:101)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:84)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:140)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:399)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:353)
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:65)
	at org.springframework.cloud.endpoint.RefreshEndpoint.refresh(RefreshEndpoint.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:61)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:102)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:93)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This `NullpointerException` occurs when you have a proxied bean without implementation in the application context (as created by `ProxyFactory.getProxy`).

`org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder#getTargetObject` returns null for the bean since `.getTargetSource()` returns an `EmptyTargetSource` which in turn returns null for `getTarget()`.

Example:
![image](https://user-images.githubusercontent.com/255721/37529065-6f74f8a2-2936-11e8-95b2-58d02d6ad00c.png)

**Comment by spencergibb** [comment]
The code in your screenshot is now gone. Can you try again with snapshots?

**Comment by Dav1dde** [comment]
Still the same problem, just a failure somewhere else:

Example:

```java
package com.example.demo;

import org.aopalliance.intercept.MethodInterceptor;
import org.springframework.aop.framework.ProxyFactory;
import org.springframework.beans.factory.FactoryBean;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;


@SpringBootApplication
public class DemoApplication {
    public static void main(String[] args) {
        ConfigurableApplicationContext applicationContext = new SpringApplicationBuilder(DemoApplication.class)
                .run(args);

        ConfigurationPropertiesRebinder rebinder = applicationContext.getBean(ConfigurationPropertiesRebinder.class);
        rebinder.rebind();
    }

    @Bean
    @ConfigurationProperties("some.service")
    public FactoryBean<SomeService> someService() {
        return new SomeFactory();
    }

    interface SomeService {
        void foo();
    }

    public static class SomeFactory implements FactoryBean<SomeService> {
        @Override
        public SomeService getObject() throws Exception {
            return ProxyFactory.getProxy(SomeService.class, (MethodInterceptor) methodInvocation -> null);
        }

        @Override
        public Class<?> getObjectType() {
            return SomeService.class;
        }
    }
}
```

Error:

```java
Exception in thread "main" java.lang.IllegalArgumentException: Disposable bean must not be null
	at org.springframework.util.Assert.notNull(Assert.java:193)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.<init>(DisposableBeanAdapter.java:144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.destroyBean(AbstractAutowireCapableBeanFactory.java:449)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:99)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:84)
	at com.example.demo.DemoApplication.main(DemoApplication.java:21)
```

Using the ` 2.0.0.BUILD-SNAPSHOT` version.

**Comment by spencergibb** [comment]
Can I ask how you get into that state?

**Comment by spencergibb** [comment]
I guess I just need to love above the exception :stuck_out_tongue_winking_eye:

**Comment by Dav1dde** [comment]
I provided an example above, I'll attach a runnable project: [cpf_1.zip](https://github.com/spring-cloud/spring-cloud-commons/files/1820160/cpf_1.zip)

The problem is a factory, that returns a proxy with no implementation (e.g. as with ` ProxyFactory.getProxy`) in combination with a bean definition that is annotated with `@ConfigurationProperties`. The `@ConfigurationProperties` annotation is inherited to the created bean, now refreshing the context leads to this broken state (bean = null in rebinder).

In a non simpliefied example that happens because we use a factory bean to configure multiple CXF JAX-RS/WS for the same interface and then create one interface using a catch-all advice to forward the call to all created clients. 

This is not the first time I have ran into problems with `@ConfigurationProperties` and factory beans (e.g. https://github.com/spring-projects/spring-boot/issues/11908 or #288) - Just to make sure - Factory beans and `@ConfigurationProperties` should work together?

**Comment by spencergibb** [comment]
> Just to make sure - Factory beans and @ConfigurationProperties should work together?

I'm not sure, @philwebb or @wilkinsona?

**Comment by Dav1dde** [comment]
The example can be further minified (no FactoryBean anymore):

```java
@SpringBootApplication
public class DemoApplication {
    public static void main(String[] args) {
        ConfigurableApplicationContext applicationContext = new SpringApplicationBuilder(DemoApplication.class)
                .run(args);

        ConfigurationPropertiesRebinder rebinder = applicationContext.getBean(ConfigurationPropertiesRebinder.class);
        rebinder.rebind();
    }

    @Bean
    @ConfigurationProperties("some.service")
    public SomeService someService() {
        return ProxyFactory.getProxy(SomeService.class, (MethodInterceptor) methodInvocation -> null);
    }

    interface SomeService {
        void foo();
    }
}
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Disposable bean must not be null
	at org.springframework.util.Assert.notNull(Assert.java:193)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.<init>(DisposableBeanAdapter.java:144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.destroyBean(AbstractAutowireCapableBeanFactory.java:449)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:99)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:84)
	at com.example.demo.DemoApplication.main(DemoApplication.java:20)
```

Granted, the code is not very useful.

**Comment by philwebb** [comment]
> Factory beans and `@ConfigurationProperties` should work together

I don't think it's a use-case we particularly anticipated and I don't think we have tests for it. Having said that, I can't see any reason off the top of my head why they shouldn't work together.

**Comment by wilkinsona** [comment]
FWIW, I don't think either of the referenced issues were specific to the `@ConfigurationProperties` bean being a factory bean.

AFAIK, Boot doesn't care if the configuration properties are being bound to a factory bean or a "normal" bean. It'll bind to anything that's passed to its bean post-processor.

**Comment by Dav1dde** [comment]
> FWIW, I don't think either of the referenced issues were specific to the @ConfigurationProperties bean being a factory bean.

You're right I linked the wrong issue, my bad.

> I don't think it's a use-case we particularly anticipated and I don't think we have tests for it. Having said that, I can't see any reason off the top of my head why they shouldn't work together.

Good! 


Back to the issue. Proposed fixes:

* Bind Properties to proxy if there is no target (setters might affect interceptor behaviour)
* Skip proxies without implementation
* Don't apply `@ConfigurationProperties` to the bean created by a Factory (still doesn't fix the problem for my second example)

**Comment by spencergibb** [comment]
I went with the only one I can control
> Skip proxies without implementation
