### ISSUE TITLE
spring boot 1.2.5 microservice will not start due to BeanCreationException: Error creating bean with name 'org.springframework.cloud.client.discovery.noop.NoopDiscoveryClientAutoConfiguration': Invocation of init method failed; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by suryab84** [spring-cloud/spring-cloud-commons#347]
Following error happens while starting spring boot 1.2.5, with jetty microcontainer:

WARN  2018-03-21 13:10:05,952 [main] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.client.discovery.noop.NoopDiscoveryClientAutoConfiguration': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)

 Caused by: java.lang.NullPointerException
	        at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.getPort(JettyEmbeddedServletContainer.java:191
	)
	        at org.springframework.cloud.client.discovery.noop.NoopDiscoveryClientAutoConfiguration.findPort(NoopDiscoveryClientAutoConfigu
	ration.java:90)
	        at org.springframework.cloud.client.discovery.noop.NoopDiscoveryClientAutoConfiguration.init(NoopDiscoveryClientAutoConfigurati
	on.java:73)
	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.lang.reflect.Method.invoke(Method.java:498)
	        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnot
	ationBeanPostProcessor.java:349)
	        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(Init
	DestroyAnnotationBeanPostProcessor.java:300)
	        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDest
	royAnnotationBeanPostProcessor.java:133)

Relevant dependencies:

[INFO]    org.springframework.boot:spring-boot:jar:1.2.5.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-actuator:jar:1.2.5.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-autoconfigure:jar:1.2.5.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter:jar:1.2.5.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-actuator:jar:1.2.5.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-jetty:jar:1.2.5.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-logging:jar:1.2.5.RELEASE:compile
[INFO]    org.springframework.boot:spring-boot-starter-web:jar:1.2.5.RELEASE:compile
[INFO]    org.springframework.cloud:spring-cloud-commons:jar:1.0.3.RELEASE:compile
[INFO]    org.springframework.cloud:spring-cloud-context:jar:1.0.3.RELEASE:compile
[INFO]    org.springframework.cloud:spring-cloud-netflix-core:jar:1.0.4.RELEASE:compile
[INFO]    org.springframework.cloud:spring-cloud-starter:jar:1.0.4.RELEASE:compile
[INFO]    org.springframework.cloud:spring-cloud-starter-ribbon:jar:1.0.4.RELEASE:compile
[INFO]    org.springframework.data:spring-data-commons:jar:1.10.2.RELEASE:compile
[INFO]    org.springframework.data:spring-data-jpa:jar:1.8.0.RELEASE:compile
[INFO]    org.eclipse.jetty:jetty-continuation:jar:8.1.7.v20120910:compile
[INFO]    org.eclipse.jetty:jetty-http:jar:8.1.7.v20120910:compile
[INFO]    org.eclipse.jetty:jetty-io:jar:8.1.7.v20120910:compile
[INFO]    org.eclipse.jetty:jetty-jsp:jar:8.1.7.v20120910:compile
[INFO]    org.eclipse.jetty:jetty-security:jar:8.1.7.v20120910:compile
[INFO]    org.eclipse.jetty:jetty-server:jar:8.1.7.v20120910:compile
[INFO]    org.eclipse.jetty:jetty-servlet:jar:8.1.7.v20120910:compile
[INFO]    org.eclipse.jetty:jetty-util:jar:8.1.7.v20120910:compile
[INFO]    org.eclipse.jetty:jetty-webapp:jar:8.1.7.v20120910:compile
[INFO]    org.eclipse.jetty:jetty-xml:jar:8.1.7.v20120910:compile
[INFO]    org.springframework:spring-aop:jar:4.1.7.RELEASE:compile
[INFO]    org.springframework:spring-beans:jar:4.1.7.RELEASE:compile
[INFO]    org.springframework:spring-context:jar:4.1.7.RELEASE:compile
[INFO]    org.springframework:spring-context-support:jar:4.1.7.RELEASE:compile
[INFO]    org.springframework:spring-core:jar:4.1.7.RELEASE:compile
[INFO]    org.springframework:spring-expression:jar:4.2.0.RELEASE:compile
[INFO]    org.springframework:spring-jdbc:jar:4.1.7.RELEASE:compile
[INFO]    org.springframework:spring-orm:jar:4.1.7.RELEASE:compile
[INFO]    org.springframework:spring-test:jar:4.1.7.RELEASE:test
[INFO]    org.springframework:spring-tx:jar:4.1.7.RELEASE:compile
[INFO]    org.springframework:spring-web:jar:4.1.7.RELEASE:compile
[INFO]    org.springframework:spring-webmvc:jar:4.1.7.RELEASE:compile

**Comment by spencergibb** [comment]
Angel and Brixton are no longer supported, can you upgrade to Dalston our Edgware?

**Comment by suryab84** [comment]
Thank you. I will give that a shot. Might try updating to a newer version of boot as well. But please keep this thread open.

**Comment by spencergibb** [comment]
You will have to upgrade boot also

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
