### ISSUE TITLE
ConfigurationPropertiesRebinder doesn't work with FactoryBeans

### ISSUE THREAD

**Issue by Squiry** [spring-cloud/spring-cloud-commons#356]
ConfigurationPropertiesRebinder can't rebind beans created with FactoryBeans ([demo](https://github.com/Squiry/spring-cloud-configuration-properties-rebinder-demo)).
Spring Boot: 2.0.1.RELEASE
Spring Cloud: Finchley.M9

**Comment by spencergibb** [comment]
What happens? (doesn't work isn't very helpful). What are the steps to run the demo?

**Comment by Squiry** [comment]
There's a test in the demo.
Stacktrace: 
```
java.lang.IllegalArgumentException: ExistingValue must be an instance of org.springframework.beans.factory.FactoryBean<java.lang.Object>

	at org.springframework.util.Assert.isTrue(Assert.java:134)
	at org.springframework.boot.context.properties.bind.Bindable.withExistingValue(Bindable.java:162)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:103)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:93)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:413)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:102)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:84)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:141)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354)
```

**Comment by Squiry** [comment]
In ConfigurationPropertiesBindingPostProcessor we have a line:
`Bindable<?> target = Bindable.of(type).withExistingValue(bean)	.withAnnotations(annotations);`
Where type is a FactoryBean (as in java config) and bean is an object produced by that factory. So the whole rebinding process fails with an exception on each EnvironmentChangeEvent. The sad part for me is that I don't even need to rebind properties on FactoryBean produced beans but it fails even without properties.

**Comment by Dav1dde** [comment]
The Problem is the following, a Binder gets instantiated with the type of the FactoryBean and the existing value of the bean created by the factory:

![image](https://user-images.githubusercontent.com/255721/41764179-9aaab9e6-7600-11e8-98af-940ff32d4d5c.png)

```java
	public Bindable<T> withExistingValue(T existingValue) {
		Assert.isTrue(
				existingValue == null || this.type.isArray()
						|| this.boxedType.resolve().isInstance(existingValue),
				"ExistingValue must be an instance of " + this.type);
		Supplier<T> value = (existingValue == null ? null : () -> existingValue);
		return new Bindable<>(this.type, this.boxedType, value, NO_ANNOTATIONS);
	}
```

`this.boxedType.resolve().isInstance(existingValue)` is what fails.

The code is withing spring-boot and not spring-cloud, should I open a bug there?

**Comment by Dav1dde** [comment]
Actually the root cause of this Problem happens within `ConfigurationPropertiesRebinder#rebind` so maybe this is a spring cloud problem after all.

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley.RELEASE?

**Comment by Dav1dde** [comment]
Yes. We're on Finchley and 2.0.3

**Comment by Squiry** [comment]
Frankly speaking using @ConfigurationProperties on FactoryBean is wrong. As a workaround we've splitted our factory beans on simple pojo with @ConfigurationProperties and just factory method that uses this pojo. And I actually think that this is the way. We just need to have some mention of this problem somewhere in spring cloud documentation.

**Comment by Dav1dde** [comment]
I've asked that in a different issue in spring boot and the consenseus was it should work it is just not tested very well.

**Comment by marcingrzejszczak** [comment]
Is there any chance to provide a test that replicates the problem?

**Comment by spencergibb** [comment]
Moving `@ConfigurationProperties` off of the factory bean is the right thing to do.

**Comment by Dav1dde** [comment]
@spencergibb Then please make it official and add it to the documentation.

Because the statement/discussion here says otherwise: https://github.com/spring-cloud/spring-cloud-commons/issues/337#issuecomment-373786086
