### ISSUE TITLE
Actuator endpoint override behaves incorrectly

### ISSUE THREAD

**Issue by illingtonFlex** [spring-cloud/spring-cloud-commons#374]
As discussed here: https://github.com/spring-cloud/spring-cloud-commons/issues/354

Although endpoints are named differently, app still fails to start.

```
 Caused by: java.lang.IllegalStateException: Found multiple extensions for the endpoint bean environmentEndpoint (environmentEndpointWebExtension, environmentWebEndpointExtension)
 	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.convertToEndpoint(EndpointDiscoverer.java:199) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
 	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.convertToEndpoints(EndpointDiscoverer.java:184) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
 	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.discoverEndpoints(EndpointDiscoverer.java:124) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
 	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.getEndpoints(EndpointDiscoverer.java:116) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
 	at org.springframework.boot.actuate.endpoint.web.PathMappedEndpoints.lambda$getEndpoints$1(PathMappedEndpoints.java:69) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
 	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_151]
```

**Comment by spencergibb** [comment]
I'm unable to reproduce this. Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

It shouldn't ever get into that state since the one from spring cloud is created first and the one in boot is conditional on missing bean.

**Comment by illingtonFlex** [comment]
Sorry, I'm not able to start a new project to try and recreate this issue. I could probably get my project into a portable state and attach it as a zip. Is that acceptable?

**Comment by spencergibb** [comment]
yes, a zip is fine.

**Comment by illingtonFlex** [comment]
Well, as I was moving my dependencies around to prepare this project to zip up, the issue resolved itself and I am no longer able to recreate it. I have been bouncing around among Spring-Boot and Finchley versions, so maybe this was a cached class file somewhere? At any rate, there would be no point in attaching the project, since it is no longer exhibiting the error.
