### ISSUE TITLE
CommonsClientAutoConfiguration creates DiscoveryClientHealthIndicator even if discovery is disabled

### ISSUE THREAD

**Issue by mdjnewman** [spring-cloud/spring-cloud-commons#4]
In the Spring Boot 1.2.1.RELEASE build combined with `org.springframework.cloud:spring-cloud-starter-hystrix:1.0.0.RC1`, I'm getting an error when hitting the /health endpoint:

```
2015-01-09 10:00:54.994 ERROR 8936 --- [nio-8080-exec-1] o.s.c.c.d.DiscoveryClientHealthIndicator : Error

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.client.discovery.DiscoveryClient] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371)
```

This seems to be caused by `CommonsClientAutoConfiguration` creating a `DiscoveryClientHealthIndicator` even if discovery is disabled.

The bootstrap.yml is:

```
spring:
  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
```

**Comment by spencergibb** [comment]
can you try with snapshot?  I believe that was fixed here e48dff74e55b5ef15b2d91d510d2404bf90aa47f

And the proper property is `spring.cloud.discovery.enabled`. `spring.cloud.config.discovery.enabled` is whether to find config server via discovery, not enabling or disabling discovery.

**Comment by mdjnewman** [comment]
I've having some problems with trying the snapshot, but you're right it looks like e48dff74e55b5ef15b2d91d510d2404bf90aa47f will fix it.

The problem with the snapshot is I think caused by the `ribbon-core` version:

```
\--- org.springframework.cloud:spring-cloud-starter-hystrix:1.0.0.BUILD-SNAPSHOT
     +--- org.springframework.cloud:spring-cloud-starter:1.0.0.BUILD-SNAPSHOT
     |    \--- org.springframework.cloud:spring-cloud-config-client:1.0.0.BUILD-SNAPSHOT
     |         +--- org.springframework.boot:spring-boot-starter:1.1.5.RELEASE -> 1.2.1.RELEASE (*)
     |         \--- org.springframework.security:spring-security-crypto:3.2.4.RELEASE
     |              \--- org.springframework:spring-core:3.2.8.RELEASE -> 4.1.4.RELEASE (*)
     +--- org.springframework.cloud:spring-cloud-netflix-core:1.0.0.BUILD-SNAPSHOT
     |    +--- org.springframework.boot:spring-boot-starter-web:1.1.5.RELEASE -> 1.2.1.RELEASE (*)
     |    +--- org.springframework.boot:spring-boot-starter-actuator:1.1.5.RELEASE -> 1.2.1.RELEASE (*)
     |    +--- com.netflix.feign:feign-ribbon:6.1.2
     |    |    +--- com.squareup.dagger:dagger:1.1.0
     |    |    |    \--- javax.inject:javax.inject:1
     |    |    +--- com.netflix.ribbon:ribbon-core:0.3.1 -> 2.0-RC9
     |    |    |    +--- com.netflix.netflix-commons:netflix-commons-util:0.1.1
     |    |    |    |    \--- org.slf4j:slf4j-api:1.6.4 -> 1.7.8
     |    |    |    +--- com.netflix.servo:servo-core:0.7.4
     |    |    |    |    +--- org.slf4j:slf4j-api:1.7.6 -> 1.7.8
     |    |    |    |    +--- com.google.guava:guava:14.0.1 -> 18.0
     |    |    |    |    \--- com.google.code.findbugs:annotations:2.0.0
     |    |    |    +--- com.google.guava:guava:14.0.1 -> 18.0
     |    |    |    +--- com.netflix.archaius:archaius-core:0.5.12
     |    |    |    |    +--- com.google.guava:guava:11.0.2 -> 18.0
     |    |    |    |    +--- org.codehaus.jackson:jackson-mapper-asl:1.9.11
     |    |    |    |    |    \--- org.codehaus.jackson:jackson-core-asl:1.9.11
     |    |    |    |    +--- commons-configuration:commons-configuration:1.8
     |    |    |    |    |    +--- commons-lang:commons-lang:2.6
     |    |    |    |    |    \--- commons-logging:commons-logging:1.1.1 -> 1.2
     |    |    |    |    +--- org.slf4j:slf4j-api:1.6.4 -> 1.7.8
     |    |    |    |    +--- org.codehaus.jackson:jackson-core-asl:1.9.11
     |    |    |    |    \--- com.google.code.findbugs:annotations:2.0.0
     |    |    |    \--- org.slf4j:slf4j-api:1.6.4 -> 1.7.8
     |    |    \--- com.netflix.feign:feign-core:6.1.2
     |    |         \--- com.squareup.dagger:dagger:1.1.0 (*)
     |    +--- com.google.guava:guava:18.0
     |    +--- org.neo4j:neo4j-cypher-compiler-2.1:2.1.2
     |    |    +--- org.parboiled:parboiled-scala_2.10:1.1.6
     |    |    |    \--- org.parboiled:parboiled-core:1.1.6
     |    |    +--- net.sf.opencsv:opencsv:2.3
     |    |    \--- org.scala-lang:scala-library:2.10.4
     |    \--- org.apache.activemq:activemq-client:5.9.1
     |         +--- org.slf4j:slf4j-api:1.7.5 -> 1.7.8
     |         +--- org.apache.geronimo.specs:geronimo-jms_1.1_spec:1.1.1
     |         +--- org.fusesource.hawtbuf:hawtbuf:1.9
     |         \--- org.apache.geronimo.specs:geronimo-j2ee-management_1.1_spec:1.0.1
     +--- com.netflix.hystrix:hystrix-core:1.4.0-RC5
     |    +--- org.slf4j:slf4j-api:1.7.0 -> 1.7.8
     |    +--- com.netflix.rxjava:rxjava-core:0.20.4
     |    \--- com.netflix.archaius:archaius-core:0.4.1 -> 0.5.12 (*)
     +--- com.netflix.hystrix:hystrix-metrics-event-stream:1.4.0-RC5
     |    +--- com.netflix.hystrix:hystrix-core:1.4.0-RC5 (*)
     |    \--- org.codehaus.jackson:jackson-core-asl:1.9.2 -> 1.9.11
     +--- com.netflix.hystrix:hystrix-javanica:1.4.0-RC5
     |    +--- commons-collections:commons-collections:3.2.1
     |    +--- org.aspectj:aspectjweaver:1.7.4
     |    +--- com.google.guava:guava:15.0 -> 18.0
     |    +--- com.netflix.hystrix:hystrix-core:1.4.0-RC5 (*)
     |    +--- com.google.code.findbugs:jsr305:2.0.0
     |    +--- org.aspectj:aspectjrt:1.7.4
     |    \--- org.apache.commons:commons-lang3:3.1
     \--- com.netflix.ribbon:ribbon-core:2.0-RC9 (*)
```

I end up with a `ClassNotFoundException`:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.List org.springframework.cloud.netflix.ribbon.RibbonAutoConfiguration.balancers; nested exception is java.lang.TypeNotPresentException: Type com.netflix.loadbalancer.BaseLoadBalancer not present
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 16 common frames omitted
Caused by: java.lang.TypeNotPresentException: Type com.netflix.loadbalancer.BaseLoadBalancer not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.s.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.FieldRepository.getGenericType(FieldRepository.java:85)
	at java.lang.reflect.Field.getGenericType(Field.java:241)
	at org.springframework.core.SerializableTypeWrapper$FieldTypeProvider.getType(SerializableTypeWrapper.java:287)
	at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:154)
	at org.springframework.core.ResolvableType.forType(ResolvableType.java:1190)
	at org.springframework.core.ResolvableType.forField(ResolvableType.java:899)
	at org.springframework.core.GenericCollectionTypeResolver.getCollectionFieldType(GenericCollectionTypeResolver.java:89)
	at org.springframework.beans.factory.config.DependencyDescriptor.getCollectionType(DependencyDescriptor.java:298)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:994)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.netflix.loadbalancer.BaseLoadBalancer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.orName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 34 common frames omitted
```

Using the Spring Boot 1.2.1.RELEASE gradle plugin, the build.gradle dependencies are:

```
dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.boot:spring-boot-starter-actuator")
    compile("org.springframework.cloud:spring-cloud-starter-hystrix:1.0.0.BUILD-SNAPSHOT")
}
```

I can open another issue for this if you think it's needed?

**Comment by spencergibb** [comment]
Yes, open another issue.
