### ISSUE TITLE
RefreshAutoConfiguration bean definition override conflicts with Spring Boot's 2.1 bean override settings

### ISSUE THREAD

**Issue by mp911de** [spring-cloud/spring-cloud-commons#400]
`RefreshAutoConfiguration$RefreshScopeBeanDefinitionEnhancer` registers bean proxies and reusing the bean name of already existing bean registrations. Upgrading to Spring Boot 2.1 causes `BeanDefinitionOverrideException` like:

```
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'dataSource' defined in BeanDefinition defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Cannot register bean definition [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]] for bean 'dataSource': There is already [Root bean: class [null]; scope=refresh; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari; factoryMethodName=dataSource; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:873) ~[spring-beans-5.1.0.RC1.jar:5.1.0.RC1]
	at org.springframework.cloud.autoconfigure.RefreshAutoConfiguration$RefreshScopeBeanDefinitionEnhancer.postProcessBeanDefinitionRegistry(RefreshAutoConfiguration.java:140) ~[spring-cloud-context-2.0.0.BUILD-20180618.115305-3010.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.0.RC1.jar:5.1.0.RC1]
```

**Comment by mp911de** [comment]
Looking at branch `upgrade-boot-2-1`, this seems to be an already known issue.

**Comment by spencergibb** [comment]
indeed. Was just about to merge it after dave had a look today.

**Comment by tokuhirom** [comment]
I want to use spring-boot 2.1 with spring cloud.  But I got the same problem.
Could you release new version?

**Comment by ryanjbaxter** [comment]
This fix is in Greenwich.M1
