### ISSUE TITLE
{cipher} password not decrypted anymore

### ISSUE THREAD

**Issue by mpalourdio** [spring-cloud/spring-cloud-commons#471]
Hello,

I have just updated from SB 2.1.2 + Greenwich RC2 to Greenwich release.

I have a spring-cloud config server, and an eureka server. Eureka server fails at start when trying to connect to my local config server. It looks like the ciphered password in bootstrap.properties is not decrypted anymore. 

`ConfigServicePropertySourceLocator#addAuthorizationToken`, receives the {cipher} password in plain text, which leads to the stack trace below.

Reverting to Greenwich.RC2 fixes the problem. 

```
java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:136) ~[spring-cloud-config-client-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.cloud.config.client.ConfigServerHealthIndicator.getPropertySource(ConfigServerHealthIndicator.java:54) ~[spring-cloud-config-client-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.cloud.config.client.ConfigServerHealthIndicator.doHealthCheck(ConfigServerHealthIndicator.java:35) ~[spring-cloud-config-client-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:84) ~[spring-boot-actuator-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:98) [spring-boot-actuator-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:50) [spring-boot-actuator-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:246) [spring-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76) [spring-boot-actuator-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:61) [spring-boot-actuator-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:126) [spring-boot-actuator-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:99) [spring-boot-actuator-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [na:1.8.0_191]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:1.8.0_191]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468) [na:1.8.0_191]
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76) [na:1.8.0_191]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309) [na:1.8.0_191]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401) [na:1.8.0_191]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) [na:1.8.0_191]
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357) [na:1.8.0_191]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) [na:1.8.0_191]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) [na:1.8.0_191]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_191]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) [na:1.8.0_191]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573) [na:1.8.0_191]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834) [na:1.8.0_191]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688) [na:1.8.0_191]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_191]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
Caused by: org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class org.springframework.cloud.config.environment.Environment] and content type [text/html;charset=UTF-8]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:121) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:994) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:977) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:669) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:578) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment(ConfigServicePropertySourceLocator.java:218) ~[spring-cloud-config-client-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:96) ~[spring-cloud-config-client-2.1.0.RELEASE.jar:2.1.0.RELEASE]
```

**Comment by ryanjbaxter** [comment]
I wonder if this might have caused the issue https://github.com/spring-cloud/spring-cloud-commons/pull/462

Is it possible the property is being overriden?

**Comment by ryanjbaxter** [comment]
Also if you could provide a sample application that reproduces the issue that would be great.

**Comment by mpalourdio** [comment]
Run this [configuration server](https://github.com/mpalourdio/ConfigServer) (localhost:8888), then run this [https://github.com/mpalourdio/DiscoveryServer](https://github.com/mpalourdio/DiscoveryServer).

Well, looks like #462 could indeed be the source cause

**Comment by mpalourdio** [comment]
I have tried to fix this regression in #472.

**Comment by skarzhevskyy** [comment]
I created a set of integration tests for decryption problems.
[playground-spring-cloud-integration-tests](https://github.com/skarzhevskyy/playground-spring-cloud-integration-tests)
verified that Config Server/ Config Client combinations used to work in Finchley
Please let me know if there are value adding this tests to spring-cloud set of integration tests and I can create PR to recommended repository

**Comment by mpalourdio** [comment]
@skarzhevskyy Thanks, much clear for me now ! From what I see, looks like reverting #462 is the way to go.

**Comment by jaarts** [comment]
The issue is actually related to https://github.com/spring-cloud/spring-cloud-commons/pull/358 (which just activated an hidden issue). The propertySources from CompositePropertySource should be walked in reversed order for the overrides to behave properly. 

With PR #473 the integration tests from @skarzhevskyy succeed again.

**Comment by mpalourdio** [comment]
Awesome, thanks for troubleshooting this!

**Comment by mpalourdio** [comment]
After freshly checking out master and testing the fix provided in #473, I still have exactly the same stacktrace. Did not have time to investigate more unfortunately for the moment.

**Comment by ryanjbaxter** [comment]
@jaarts the problem is actually here 
https://github.com/spring-cloud/spring-cloud-commons/blob/ae314100f5340ab6fd7f49995ec2c6f478b9bc70/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java#L224

What happens is that we have two property sources one with the encrypted `spring.cloud.config.password` property and one with the decrypted `spring.cloud.config.password` value.  We come across the encrypted one first and add it to `overrides`.  But when we come across the decrypted value from the second property source, we remove the property from the `overrides` and therefore never decrypt the password before making the request to the config server.  I am thinking that I am going to try and revert both PRs for now to restore the functionality until we come up with the correct solution.

**Comment by mpalourdio** [comment]
Thanks for investigating. I had come to the same conclusions in #472. After digging around, looks like a revert is a sane beginning, and maybe the test suite could be then hardened before re-implementing this kind of optimizations.

**Comment by ryanjbaxter** [comment]
Actually looks like both https://github.com/spring-cloud/spring-cloud-commons/pull/459 and https://github.com/spring-cloud/spring-cloud-commons/pull/462 need to be reverted in the 2.0.x branch.  If you use Finchley.BUILD-SNAPSHOT the same issue will happen.

I am also going to revert https://github.com/spring-cloud/spring-cloud-commons/pull/473 in master most likely but I need to test that out.

**Comment by jaarts** [comment]
I do not completely understands what happens, but do what you think is best.

If the property is overridden by source 2, then you don't need the first one anymore, right?
Unless you use the two sources separately, but then having 1 overrides source doesn't make sense.

**Comment by ryanjbaxter** [comment]
I am not 100% exactly what happens but here is what I think happens.  We create a separate property source object for the properties that need to be decrypted.  So after the first time we load properties (in this case for the bootstrap) we end up with an additional property source since `spring.cloud.config.password` is encrypted.  Then when we load the properties from the config server and again run through the code to decrypt the properties we again decrypt `spring.cloud.config.password` but since there is now another property source, the decrypt property source, with that property we end up removing it from the overrides, and never decrypt it.

**Comment by ryanjbaxter** [comment]
Everything is reverted both in the 2.0.x branch and master.  @mpalourdio can you test with both Finchley.BUILD-SNAPSHOT and Greenwich.BUILD-SNAPSHOT?

**Comment by jaarts** [comment]
Isn't the solution then to either remove the `decrypted` property source or ignore the it during subsequent decryption runs?

A quick test with the setup from https://github.com/spring-cloud/spring-cloud-commons/issues/471#issuecomment-457090908 and first replacing the `decrypted` property source with an empty source, seems to fix the issue:
```java
	@Override
	public void initialize(ConfigurableApplicationContext applicationContext) {

		ConfigurableEnvironment environment = applicationContext.getEnvironment();
		MutablePropertySources propertySources = environment.getPropertySources();

                // new line:
		insert(applicationContext, new SystemEnvironmentPropertySource(
				DECRYPTED_PROPERTY_SOURCE_NAME, Collections.emptyMap()));
```

**Comment by mpalourdio** [comment]
> Everything is reverted both in the 2.0.x branch and master. @mpalourdio can you test with both Finchley.BUILD-SNAPSHOT and Greenwich.BUILD-SNAPSHOT?

Thanks, I will do this later afternoon and let you know.

**Comment by ryanjbaxter** [comment]
@jaarts it might be but we are trying to do a release today so we needed to remove the problematic code.  Please submit another PR for this and we can take a look.

**Comment by mpalourdio** [comment]
@ryanjbaxter 

I took some time to tests :
- SB 2.0.8-RELEASE + Finchley.BUILD-SNAPSHOT = **OK**
- SB 2.1.2-RELEASE + Greenwich.BUILD-SNAPSHOT = **OK**

Thanks !

**Comment by sadab323** [comment]
In IMDSV1 WORKING FINE BUT IMDSV2 IT IS GIVING Cannot decrypt error why?
