### ISSUE TITLE
InetUtils.getFirstNonLoopbackHostInfo may be slow

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-commons#55]
I'm seeing very slow start times in dataflow admin due to some calls into network stack by cloud classes.

Took trace and indeed if I manually test `InetUtils.getFirstNonLoopbackHostInfo()`, it takes between 6-9 secs in my system. I can probably solve this in my system but wanted to post it here because most likely other users will hit same issues and it's a little difficult to track down unless you look more closely why startup is blocked.

We could try to fix this in cloud classes(is it even fixable?) or possibly log something so that user could identify this problem more quickly(and maybe add something to docs).

I'm using `SpringApplicationBuilder` manually within existing admin app to get a fresh context to run some stuff there(I get all nice boot goodies that way). I hit this slowness every single time because I don't control admin classpath and I believe cloud is adding something automatically.

```
"main" #11 prio=5 os_prio=0 tid=0x00007f1bec26e000 nid=0x208a runnable [0x00007f1bd4df1000]
   java.lang.Thread.State: RUNNABLE
	at java.net.Inet6AddressImpl.getHostByAddr(Native Method)
	at java.net.InetAddress$2.getHostByAddr(InetAddress.java:911)
	at java.net.InetAddress.getHostFromNameService(InetAddress.java:596)
	at java.net.InetAddress.getHostName(InetAddress.java:538)
	at java.net.InetAddress.getHostName(InetAddress.java:510)
	at org.springframework.cloud.util.InetUtils.convert(InetUtils.java:71)
	at org.springframework.cloud.util.InetUtils.getFirstNonLoopbackHostInfo(InetUtils.java:28)
	at org.springframework.cloud.client.HostInfoEnvironmentPostProcessor.postProcessEnvironment(HostInfoEnvironmentPostProcessor.java:29)
	at org.springframework.boot.env.EnvironmentPostProcessingApplicationListener.onApplicationEvent(EnvironmentPostProcessingApplicationListener.java:51)
	at org.springframework.boot.env.EnvironmentPostProcessingApplicationListener.onApplicationEvent(EnvironmentPostProcessingApplicationListener.java:40)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	- locked <0x000000071d716768> (a java.util.concurrent.atomic.AtomicBoolean)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:126)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:75)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:55)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:980)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969)
	at org.springframework.cloud.dataflow.admin.AdminApplication.main(AdminApplication.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dsyer** [comment]
Hotel wifi?

**Comment by pperalta** [comment]
Looks like this can be caused by DNS issues:

http://www-01.ibm.com/support/docview.wss?uid=swg21170467
https://issues.jboss.org/browse/JBAS-3794

Perhaps try `-Djava.net.preferIPv4Stack=true` as a JVM option?

**Comment by jvalkeal** [comment]
This is my own wifi and laptop. I'll bet it's about dns settings or something similar. But if it happened to me, it will happen to others too.

**Comment by pperalta** [comment]
Yeah this is an interesting problem. If you want to maintain the existing contract of `InetUtils.getFirstNonLoopbackHostInfo()` then the only thing you can do is look up the host name on a separate thread and either return some kind of value (`localhost`) or throw an exception if it takes too long to return. Alternatively, you could offer a `InetUtils.getFirstNonLoopbackHostInfo()` that returns `Future` so the caller can decide how long it wants to wait for a result.

**Comment by jvalkeal** [comment]
btw `-Djava.net.preferIPv4Stack=true` didn't help.

Think this is simply caused by dns timeout:
```
$ time nslookup 192.168.8.102
Server:		127.0.1.1
Address:	127.0.1.1#53

** server can't find 102.8.168.192.in-addr.arpa: NXDOMAIN


real	0m8.395s
```

I'm a bit worried if we hit this in a paas system where it's literally impossible to debug it remotely.

**Comment by jvalkeal** [comment]
btw, adding ip to `/etc/hosts` makes `InetUtils` fast again.
```
192.168.8.102  neo-wifi
```
