### ISSUE TITLE
RestTemplate bean issue since Brixton.M3

### ISSUE THREAD

**Issue by kakawait** [spring-cloud/spring-cloud-commons#66]
From following documentation http://projects.spring.io/spring-cloud/spring-cloud.html#_multiple_resttemplate_objects if I need a simple `RestTemplate` without *load balancing* I should create my own bean and inject it as usual.

Using `Brixton.M2` I get the following (simplified) code:

```java
@Configuration
public FooConfiguration {
    @Primary
    @Bean
     public RestTemplate restTemplate() {
         return new RestTemplate();
     }

    @Primary
    @Bean
    public Foo foo() {
        return new Foo();
    }
}
```

where `Foo` is

```java
public class Foo {
    @Inject
    private RestTemplate restTemplate;
}
```

Works great but when using `Brixton.M3` I have the following error:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.web.client.RestTemplate com.my.app.Foo.restTemplate; nested exception is java.lang.IllegalArgumentException: Can not set org.springframework.web.client.RestTemplate field com.my.app.Foo.restTemplate to com.sun.proxy.$Proxy89
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 82 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can not set org.springframework.web.client.RestTemplate field com.my.app.Foo.restTemplate to com.sun.proxy.$Proxy89
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_65]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_65]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[na:1.8.0_65]
	at java.lang.reflect.Field.set(Field.java:764) ~[na:1.8.0_65]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 84 common frames omitted
```

**Comment by dsyer** [comment]
Try to `@Inject` a `RestOperations` instead (or set `spring.aop.proxyTargetClass=true`).

**Comment by kakawait** [comment]
@dsyer yes using `RestOperations` works great. Thank you for your time! I let you close it after documentation enhancement or I can close it now?

**Comment by dsyer** [comment]
We'll leave it for docs updates thanks.

**Comment by kakawait** [comment]
@dsyer I have same issue on `org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration` 

```
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.security.oauth2.client.OAuth2RestTemplate org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration.restTemplate; nested exception is java.lang.IllegalArgumentException: Can not set org.springframework.security.oauth2.client.OAuth2RestTemplate field org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration.restTemplate to com.sun.proxy.$Proxy87
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 55 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can not set org.springframework.security.oauth2.client.OAuth2RestTemplate field org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration.restTemplate to com.sun.proxy.$Proxy87
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_65]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_65]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[na:1.8.0_65]
	at java.lang.reflect.Field.set(Field.java:764) ~[na:1.8.0_65]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 57 common frames omitted
```

May I need to force `spring.aop.proxyTargetClass=true` or it possible to upgrade `org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration`
