### ISSUE TITLE
KubernetesServiceInstance getSchema returns extra "://"

### ISSUE THREAD

**Issue by bradfordChiang** [spring-cloud/spring-cloud-commons#661]
**Describe the bug**
Spring Cloud version: Hoxton.RELEASE
JDK 11
I use the lb://some-service-name to locate the pods ip from Kubernetes.
But found the the composed uri  have extra :// which cause an uri exception:
I use spring cloud loadbalancer to do the client load balancing instead of ribbon.
And it works with Eureka as the service registry, but not for Kubernetes.
I have debugged it, found the KubernetesServiceInstance's getSchema returns http:// instead of http
which cause the issue as the URI class's toString will appen :// to the uri.

```
used by: java.net.URISyntaxException: Expected hostname at index 7: http://://172.17.0.4:8180/test/swagger-ui.html
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
	at java.base/java.net.URI$Parser.parseHostname(URI.java:3451)
	at java.base/java.net.URI$Parser.parseServer(URI.java:3297)
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3216)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3158)
	at java.base/java.net.URI$Parser.parse(URI.java:3114)
	at java.base/java.net.URI.<init>(URI.java:685)
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:512)
	at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.doReconstructURI(LoadBalancerUriTools.java:111)
	at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.reconstructURI(LoadBalancerUriTools.java:95)
	at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.lambda$filter$0(ReactiveLoadBalancerClientFilter.java:108)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:177)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:91)
	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:38)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:396)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:636)
```

**Comment by bradfordChiang** [comment]
Hello @spencergibb 
This is issue happens at doOnNext@ReactiveLoadBalancerClientFilter.
Is it necessary to call that reconstructURI in doOnNext? Thanks

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by bradfordChiang** [comment]
Sorry!
The 
  ```org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.RibbonServer```'s `getSchema()`  returns `http` or `https`. But the 
  ```org.springframework.cloud.kubernetes.discovery.KubernetesServiceInstance``` 
returns `http://` or `https://`, and the 
  ```org.springframework.web.util.HierarchicalUriComponents.toUri``` will append `://` to the uri which generates a request of `http://://172.17.0.4:8180` .

**Comment by wansong** [comment]
I also encountered the exactly same issue, it is a bug. is there any update?
