### ISSUE TITLE
No qualifying bean of type ReactorLoadBalancerExchangeFilterFunction

### ISSUE THREAD

**Issue by pablo53** [spring-cloud/spring-cloud-commons#702]
Even though, spring-webflux-5.2.3.RELEASE and spring-cloud-starter-loadbalancer-2.2.1.RELEASE are on the classpath, SpringBoot failes to load the context with exception:

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.client.loadbalancer.reactive.ReactorLoadBalancerExchangeFilterFunction' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1695)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1253)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 136 more
```

This is unlike what https://github.com/spring-cloud/spring-cloud-commons/blob/master/docs/src/main/asciidoc/spring-cloud-commons.adoc#webflux-with-reactive-loadbalancer states: "If you add Spring Cloud LoadBalancer starter to your project and if spring-webflux is on the classpath, ReactorLoadBalancerExchangeFilterFunction is auto-configured.". I just followed the example there...

**Comment by spencergibb** [comment]
Please share your dependencies

**Comment by pablo53** [comment]
Among others, these are:
```
	dependencies {
		implementation("org.springframework.boot:spring-boot-starter-webflux:2.2.4.RELEASE")
		implementation("org.springframework.cloud:spring-cloud-starter-loadbalancer:2.2.1.RELEASE")
...
	}

**Comment by spencergibb** [comment]
Not sure that helps me much? Any reason you are not using the bom to manage versions? Can you provide the auto configuration report with `--debug=true`?

**Comment by pablo53** [comment]
[sprinttest.zip](https://github.com/spring-cloud/spring-cloud-commons/files/4312369/sprinttest.zip)
Pls see attached a minimal example, which gives me similar error. This one is managed by bom.

**Comment by spencergibb** [comment]
You are looking at the master docs where conditions have changed, but your app is using Hoxton, which is commons 2.2.x

https://github.com/spring-cloud/spring-cloud-commons/blob/2.2.x/docs/src/main/asciidoc/spring-cloud-commons.adoc#webflux-with-reactive-loadbalancer

You need to add `spring.cloud.loadbalancer.ribbon.enabled=false`.
