### ISSUE TITLE
HealthCheckServiceInstanceListSupplierTests.shouldCancelSubscription() times out in CI

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#716]
```
Error Message
Assertion condition defined as a lambda expression in org.springframework.cloud.loadbalancer.core.HealthCheckServiceInstanceListSupplierTests that uses java.util.concurrent.atomic.AtomicInteger 
Expecting <AtomicInteger(0)> to have value:
  <1>
but did not within 10 seconds.
Stacktrace
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a lambda expression in org.springframework.cloud.loadbalancer.core.HealthCheckServiceInstanceListSupplierTests that uses java.util.concurrent.atomic.AtomicInteger 
Expecting <AtomicInteger(0)> to have value:
  <1>
but did not within 10 seconds.
	at org.springframework.cloud.loadbalancer.core.HealthCheckServiceInstanceListSupplierTests.shouldCancelSubscription(HealthCheckServiceInstanceListSupplierTests.java:488)
Caused by: java.lang.AssertionError: 

Expecting <AtomicInteger(0)> to have value:
  <1>
but did not.
	at org.springframework.cloud.loadbalancer.core.HealthCheckServiceInstanceListSupplierTests.lambda$shouldCancelSubscription$9(HealthCheckServiceInstanceListSupplierTests.java:489)
```
@robotmrv could you have a look?

**Comment by spencergibb** [comment]
See d5dc4465b2291075cddc2fb5f5509a6af5febe4a for ignored test
