### ISSUE TITLE
Spring Boot 2 gives null placeholders in bootstrap.properties 

### ISSUE THREAD

**Issue by mehtakaran9** [spring-cloud/spring-cloud-commons#748]
I have configured spring boot application to take properties from my environment but strangely I am facing an error while starting my application. I have added the properties in my `~/.bash_profile` and also did `source ~/.bash_profile` after adding them to the profile.

bash_profile:
```
export VAULT_ENABLE=true
export VAULT_SCHEME=http
export VAULT_HOST=vault-1.dev.lokal
export VAULT_PORT=8200
export VAULT_TOKEN=5F97X
```

This is how my `bootstrap.properties` look like:
```
spring.application.name=gamification
spring.cloud.vault.enabled=${VAULT_ENABLE:true}
spring.cloud.vault.fail-fast=false
spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.scheme=${VAULT_SCHEME}
spring.cloud.vault.host=${VAULT_HOST}
spring.cloud.vault.port=${VAULT_PORT:8200}
```

This is the error I am facing:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.vault.config.VaultReactiveBootstrapConfiguration]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Scheme must be http or https
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:216) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
    ... 30 common frames omitted
Caused by: java.lang.IllegalArgumentException: Scheme must be http or https
    at org.springframework.util.Assert.isTrue(Assert.java:118) ~[spring-core-5.2.4.RELEASE.jar:5.2.4.RELEASE]
    at org.springframework.vault.client.VaultEndpoint.setScheme(VaultEndpoint.java:167) ~[spring-vault-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
    at org.springframework.cloud.vault.config.VaultConfigurationUtil.createVaultEndpoint(VaultConfigurationUtil.java:91) ~[spring-cloud-vault-config-2.2.2.RELEASE.jar:2.2.2.RELEASE]
    at org.springframework.cloud.vault.config.VaultReactiveBootstrapConfiguration.<init>(VaultReactiveBootstrapConfiguration.java:110) ~[spring-cloud-vault-config-2.2.2.RELEASE.jar:2.2.2.RELEASE]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_231]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_231]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_231]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_231]
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:203) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
    ... 32 common frames omitted

```

I added a debug point in Vault Endpoint and found this: Here as you can see, the VAULT_HOST is being taken as VAULT_HOST instead of the value of that environment variable, and same with the VAULT_SCHEME

<img width="997" alt="Screenshot 2020-05-02 at 4 02 46 AM" src="https://user-images.githubusercontent.com/22137222/80848440-e82fff80-8c30-11ea-9516-87ac892c84ce.png">

**Comment by spencergibb** [comment]
I'm unable to reproduce the problem with a minimal app.

```bash
export MY_ENV=myval
```
with this bootstrap.yaml
```yaml
my.value: ${MY_ENV}

management.endpoints.web.exposure.include: '*'
```
returns this in `/actuator/env`
```json
   {
      "name": "applicationConfig: [classpath:/bootstrap.yml]",
      "properties": {
        "my.value": {
          "value": "myval",
          "origin": "class path resource [bootstrap.yml]:1:11"
        },
        "management.endpoints.web.exposure.include": {
          "value": "*",
          "origin": "class path resource [bootstrap.yml]:3:44"
        }
      }
    },
```

Further, when I bring in `spring-cloud-starter-vault-config` and add 
```
spring.cloud.vault.scheme: ${VAULT_SCHEME}
```
to bootstrap with env `VAULT_SCHEME=http`

When I get to `    at org.springframework.cloud.vault.config.VaultConfigurationUtil.createVaultEndpoint(VaultConfigurationUtil.java:91)` the scheme is correct.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by mehtakaran9** [comment]
@spencergibb  Did you put `export MY_ENV=myval` in your bash_profile?

**Comment by mehtakaran9** [comment]
**[UPDATE]**
I made a shell script `setenv.sh` with the following:
```
#!/bin/bash

launchctl setenv VAULT_ENABLE true
launchctl setenv VAULT_SCHEME http
launchctl setenv VAULT_HOST vault-1.dev.lokal
launchctl setenv VAULT_PORT 8200
launchctl setenv VAULT_TOKEN 5F97XdGj

```

And run this using `sudo sh setenv.sh` and now it's able to recognize the environment variables for some reason. Isn't that weird?

**Comment by spencergibb** [comment]
I don't know, but it's nothing to do with spring cloud. All of that functionality comes from boot.
