### ISSUE TITLE
LoadBalancerCacheAutoConfiguration fails with missing CaffeineCacheManager

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-commons#878]
In a `spring-cloud-dataflow` with boot `2.4.1` and cloud `2020.0.0` we simply use `spring-cloud-starter-kubernetes-client-config` and end up with:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'caffeineLoadBalancerCacheManager' defined in class path resource [org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfiguration$CaffeineLoadBalancerCacheManagerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.loadbalancer.cache.LoadBalancerCacheManager]: Factory method 'caffeineLoadBalancerCacheManager' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/cache/caffeine/CaffeineCacheManager
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
```

Looks like this is because nobody pulls in `spring-context-support` where `org.springframework.cache.caffeine.CaffeineCacheManager` is and lb auto-config doesn't guard against this scenario.

**Comment by spencergibb** [comment]
So `Caffeine` is on the classpath, but `CaffeineCacheManager` is not?

**Comment by jvalkeal** [comment]
Essentially yes, that's what happened. You can see from those linked issues that for now I had to manually add `spring-context-support` to deps.
