### ISSUE TITLE
NamedContextFactory.destroy() doesn't close any ApplicationContext

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-commons#91]
The `destroy()` method doesn't actually close any of the application context. The following piece of code:
```
@Override
public void destroy() {
    Collection<AnnotationConfigApplicationContext> values = this.contexts.values();
    this.contexts.clear();
    for (AnnotationConfigApplicationContext context : values) {
        context.close();
    }
}
```

The javadoc for `contexts.values()` says:
> Returns a {@link Collection} view of the values contained in this map. The collection is backed by the map, so changes to the map are reflected in the collection, and vice-versa.

The call to `contexts.clear()` therefore also clears the `values` local variable that becomes empty when entering the for loop...

**Comment by spencergibb** [comment]
Nice catch

**Comment by brenuart** [comment]
Please note that Brixton.M3 is also affected by this problem (cfr. `SpringClientFactory`)

**Comment by brenuart** [comment]
If you manage to solve this issue and properly close application contexts created for Ribbon clients, you may come to the following - unfortunately famous - exception on shutdown:
```
17:47:03.019  INFO [           main]  --- o.s.c.a.AnnotationConfigApplicationContext         : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@3fe9b2ea: startup date [Mon Feb 22 17:47:02 CET 2016]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3dcca436
17:47:03.021  INFO [           main]  --- com.netflix.util.concurrent.ShutdownEnabledTimer   : Shutdown hook removed for: NFLoadBalancer-PingTimer-status500
17:47:03.024 DEBUG [           main]  --- com.netflix.http4.MonitoredConnectionManager       : Shutting down
17:47:03.024 DEBUG [           main]  --- com.netflix.http4.NamedConnectionPool              : Closing connection [{}->http://localhost:8080][null]
17:47:03.025 DEBUG [           main]  --- org.apache.http.impl.conn.DefaultClientConnection  : Connection 0.0.0.0:61255<->127.0.0.1:8080 closed
17:47:03.030  INFO [           main]  --- com.netflix.util.concurrent.ShutdownEnabledTimer   : Shutdown hook removed for: NFLoadBalancer-PingTimer-status500
17:47:03.035  WARN [           main]  --- com.netflix.servo.jmx.JmxMonitorRegistry           : Unable to un-register Monitor:MonitorConfig{name=LoadBalancer_status500, tags=class=ZoneAwareLoadBalancer, policy=DefaultPublishingPolicy}

javax.management.InstanceNotFoundException: com.netflix.servo:name=NumUpdateCyclesMissed,class=ZoneAwareLoadBalancer,id=LoadBalancer_status500,level=INFO,type=GAUGE
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[na:1.7.0_79]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427) ~[na:1.7.0_79]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415) ~[na:1.7.0_79]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546) ~[na:1.7.0_79]
	at com.netflix.servo.jmx.JmxMonitorRegistry.unregister(JmxMonitorRegistry.java:125) ~[servo-core-0.10.0.jar:0.10.0]
	at com.netflix.servo.DefaultMonitorRegistry.unregister(DefaultMonitorRegistry.java:143) [servo-core-0.10.0.jar:0.10.0]
	at com.netflix.servo.monitor.Monitors.unregisterObject(Monitors.java:197) [servo-core-0.10.0.jar:0.10.0]
	at com.netflix.loadbalancer.BaseLoadBalancer.shutdown(BaseLoadBalancer.java:901) [ribbon-loadbalancer-2.1.0.jar:2.1.0]
	at com.netflix.loadbalancer.DynamicServerListLoadBalancer.shutdown(DynamicServerListLoadBalancer.java:375) [ribbon-loadbalancer-2.1.0.jar:2.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:354) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:277) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:972) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:979) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
```

This is caused by the `RestClient` trying to close the LoadBalancer. However, the LoadBalancer instance has been given to the RestClient so I don't think it is its responsibility to shut it down... I managed to get rid of the exception by overriding `RestClient.destroy()` method.

**Comment by spencergibb** [comment]
@brenuart for milestones we don't go back and fix them, the next milestone (or Release Candidate) will have the fix. For the servo problem, it should be fixed in 0.10.1 (https://github.com/spring-cloud/spring-cloud-netflix/issues/809).

**Comment by brenuart** [comment]
@spencergibb Just as a reminder, but the `FeignClientFactory` available in Brixton.M3 suffers from the same problem. Not sure it has been refactored to use the `NamedContextFactory` tho...

**Comment by spencergibb** [comment]
@brenuart it has moved to `NamedContextFactory` so it's taken care of. This kind of stuff was exactly the reason I wanted to do it, so fixes could come in one class.
