### ISSUE TITLE
restart actuator is broken with Undertow

### ISSUE THREAD

**Issue by edouardhue** [spring-cloud/spring-cloud-commons#910]
With Spring Cloud 2020.0.1 and Undertow, calling the restart actuator fails and the application halts.

**How to reproduce**

1. Create a new project with Initializr and select Spring Boot 2.4.3, Java 15, Jar packaging, Spring Web, Boot Actuator and Cloud  Bootstrap dependencies.
2. Exclude the Tomcat dependency and add the Undertow starter
3. Run the application, enabling the restart endpoint
4. Call the endpoint, see the application fail.

**Sample POM**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.3</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>15</java.version>
		<spring-cloud.version>2020.0.1</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Command line to start with the restart actuator**

```bash
java -Dmanagement.endpoints.enabled-by-default=true -Dmanagement.endpoints.web.exposure.include='*' -jar target/demo-0.0.1-SNAPSHOT.jar
```

**Calling the actuator**

```bash
curl --request POST 'http://localhost:8080/actuator/restart'
```

**Console output**

```
2021-02-22 12:42:51.592  INFO 8039 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
2021-02-22 13:49:11.082  INFO 8039 --- [       Thread-3] io.undertow                              : stopping server: Undertow - 2.2.4.Final
2021-02-22 13:49:11.090  INFO 8039 --- [       Thread-3] io.undertow.servlet                      : Destroying Spring FrameworkServlet 'dispatcherServlet'
2021-02-22 13:49:11.097  INFO 8039 --- [       Thread-3] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2021-02-22 13:49:11.147 ERROR 8039 --- [       Thread-3] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: UT015023: This Context has been already destroyed
	at io.undertow.servlet.spec.ServletContextImpl.getDeploymentInfo(ServletContextImpl.java:211) ~[undertow-servlet-2.2.4.Final.jar!/:2.2.4.Final]
	at io.undertow.servlet.spec.ServletContextImpl.getInitParameter(ServletContextImpl.java:433) ~[undertow-servlet-2.2.4.Final.jar!/:2.2.4.Final]
	at org.springframework.web.context.support.ServletContextPropertySource.getProperty(ServletContextPropertySource.java:47) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.context.support.ServletContextPropertySource.getProperty(ServletContextPropertySource.java:33) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:68) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.core.env.AbstractPropertyResolver.getProperty(AbstractPropertyResolver.java:175) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:604) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.cloud.util.PropertyUtils.bootstrapEnabled(PropertyUtils.java:49) ~[spring-cloud-context-3.0.1.jar!/:3.0.1]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:99) ~[spring-cloud-context-3.0.1.jar!/:3.0.1]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:77) ~[spring-cloud-context-3.0.1.jar!/:3.0.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.cloud.context.restart.RestartEndpoint.doRestart(RestartEndpoint.java:144) ~[spring-cloud-context-3.0.1.jar!/:3.0.1]
	at org.springframework.cloud.context.restart.RestartEndpoint.safeRestart(RestartEndpoint.java:110) ~[spring-cloud-context-3.0.1.jar!/:3.0.1]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

2021-02-22 13:49:11.148  INFO 8039 --- [       Thread-3] o.s.c.context.restart.RestartEndpoint    : Could not doRestart: UT015023: This Context has been already destroyed
```

It might be related to #483.

**Comment by spencergibb** [comment]
I'm not sure how we would go about doing anything with this. Undertow is basically unmaintained.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
