### ISSUE TITLE
DecryptEnvironmentPostProcessor/TextEncryptorConfigBootstrapper appears to unintentionally make spring-security-crypto mandatory

### ISSUE THREAD

**Issue by chadlwilson** [spring-cloud/spring-cloud-commons#912]
**Describe the bug**

In previous Spring Cloud w/ Spring Boot usages, it was possible to exclude `spring-security-crypto` if you didn't need it without getting `ClassDefNotFoundError`s on application context startup. I believe the auto-configuration is intended to have conditionals to avoid such a dependency.

Also the code [here](https://github.com/spring-cloud/spring-cloud-commons/blob/5bbe5331b795386da86d7b7cc98da0fb25ab5ea2/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/TextEncryptorConfigBootstrapper.java#L48) appears to try and make it optional, however there is [an import reference in the code](https://github.com/spring-cloud/spring-cloud-commons/blob/5bbe5331b795386da86d7b7cc98da0fb25ab5ea2/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/TextEncryptorConfigBootstrapper.java#L31), so you will get a failed startup if it's not on the classpath, making the `ClassUtils` check ineffective, which is possibly unintentional.

During normal app startup with sleuth enabled:
```
java.lang.NoClassDefFoundError: org/springframework/security/crypto/encrypt/TextEncryptor
        	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        	at org.springframework.cloud.bootstrap.encrypt.DecryptEnvironmentPostProcessor.getTextEncryptor(DecryptEnvironmentPostProcessor.java:92)
        	at org.springframework.cloud.bootstrap.encrypt.DecryptEnvironmentPostProcessor.postProcessEnvironment(DecryptEnvironmentPostProcessor.java:68)
```

or, during `SpringBootTest`s that automate `ApplicationContext` load:

```
Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.boot.Bootstrapper : org.springframework.cloud.bootstrap.TextEncryptorConfigBootstrapper
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:467)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:449)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:442)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:283)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:264)
	at org.springframework.boot.test.context.SpringBootContextLoader.getSpringApplication(SpringBootContextLoader.java:132)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:90)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 82 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/security/crypto/encrypt/TextEncryptor
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:462)
	... 90 common frames omitted
```

I'm really not familiar with the bootstrapping process of Spring Cloud and we have no intention to use it or the post-processos; we just have regular Spring Cloud Sleuth usage integrated with Spring Boot autoconfiguration. 

**Environment**
Spring Boot: `2.4.3`
Spring Cloud: `2020.0.1`
Spring Cloud Sleuth only

```groovy
plugins {
    id 'java'
    id 'org.springframework.boot' version '2.4.3'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-dependencies:2020.0.1'
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-sleuth'
    implementation 'org.springframework.cloud:spring-cloud-sleuth-zipkin'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

**Additional info**

Setting `spring.cloud.bootstrap.enabled=true` seems to disable the `DecryptEnvironmentPostProcessor` for some reason but that doesn't seem to stop the `TextEncryptorConfigBootstrapper` being used during automated tests, so I haven't found a workaround for this.

**Comment by chadlwilson** [comment]
May relate to #897
