### ISSUE TITLE
Error in InetUtilsProperties.timeoutSeconds

### ISSUE THREAD

**Issue by GuiForget** [spring-cloud/spring-cloud-commons#99]
I don't believe I'm doing anything funky, I'm simply using spring-cloud-consul with Brixton.M5 and I'm getting this error:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private 
int org.springframework.cloud.util.InetUtilsProperties.timeoutSeconds; nested exception is 
org.springframework.beans.TypeMismatchException: Failed to convert value of type [java.lang.String] to
required type [int]; nested exception is java.lang.NumberFormatException: For input string:
"${spring.util.timeout.sec:${SPRING_UTIL_TIMEOUT_SEC:1}}"
```

**Comment by dsyer** [comment]
Looks like you disable some auto configuration. Can you share your code?

**Comment by GuiForget** [comment]
Indeed. I have these:
```
@Import({ConsulAutoConfiguration.class, ConsulDiscoveryClientConfiguration.class,
        RibbonAutoConfiguration.class, RibbonConsulAutoConfiguration.class,
        LoadBalancerAutoConfiguration.class})
```

I did try to add `UtilAutoConfiguration.class` but that didn't solve the problem. If I need to provide you with a sample code to reproduce the issue let me know.

**Comment by dsyer** [comment]
If you don't use `@EnableAutoConfiguration` you will need to provide a `PropertyPlaceholderConfigurer` (e.g. with `PropertyPlaceholderAutoConfiguration`).

**Comment by GuiForget** [comment]
Thank you for finding my own error.

**Comment by dsyer** [comment]
Your most welcome

**Comment by derohit** [comment]
@dsyer  @GuiForget I am also facing the same issue please if possible share the code used for the PropertyPlaceholderAutoConfiguration. 
Exception coming is Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.commons.util.InetUtilsProperties#3311b9b9': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'SPRING_UTIL_TIMEOUT_SEC:1' in value "spring.util.timeout.sec:${SPRING_UTIL_TIMEOUT_SEC:1}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1268)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:299)

**Comment by spencergibb** [comment]
@derohit `@EnableAutoConfiguration`.

**Comment by derohit** [comment]
@spencergibb thanks for the reply i am using xml based bean configuration any idea how to do it there

**Comment by yingshanlv** [comment]
@spencergibb I am facing the same question，and added @EnableAutoConfiguration，it's not work
